# Rabby iOS Native Wallet Podfile
# 纯原生Swift实现

platform :ios, '15.0'
use_frameworks!
inhibit_all_warnings!

target 'RabbyMobile' do
  # 核心加密库
  pod 'CryptoSwift', '~> 1.8'        # Keccak256, AES等加密算法
  
  # Web3以太坊库
  pod 'web3.swift', '~> 1.6'          # 以太坊工具集 + secp256k1支持
  
  # 大整数运算 (Wei转换)
  pod 'BigInt', '~> 5.0'              # 大数运算用于ETH金额计算
  
  # WalletConnect v2
  pod 'WalletConnectSwiftV2', '~> 1.9' # WalletConnect v2协议
  
  # WebSocket (WalletConnect依赖)
  pod 'Starscream', '~> 4.0'          # WebSocket通信
  
  # 网络请求
  pod 'Alamofire', '~> 5.8'           # HTTP网络请求
  
  # 图片缓存加载 (Token/NFT icons)
  pod 'Kingfisher', '~> 7.10'         # 异步图片加载与缓存
  
  # 二维码生成
  pod 'EFQRCode', '~> 6.2'            # 二维码生成(收款)
  
  # Keychain安全存储
  pod 'KeychainAccess', '~> 4.2'      # Keychain简化封装
  
  # Lottie动画 (加载/成功动效)
  pod 'lottie-ios', :git => 'https://gitee.com/mirrors/lottie-ios.git', :tag => '4.6.0'
  
  # 开发工具
  pod 'SwiftLint', '~> 0.54', :configurations => ['Debug']
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
      config.build_settings['ENABLE_BITCODE'] = 'NO'
      config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
    end
  end
end
